name: CalvinKaiKu
favicon: null
layout_spectrum: 0.6292587351053953
typography_spectrum: 0.7813751767389476
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.31154339388012886
  lightness: 0.257666630204767
  saturation: 0.6939358178060502
  rhythmicContrast: 0.5197006256785244
purpose: []
