name: CalvinKaiKu
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Illusionist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0f1110'
    - '#f9f8f4'
    - '#aca684'
    - '#ff1d1f'
    - '#ff6548'
  brandStrength: 0.31154339388012886
  lightness: 0.257666630204767
  saturation: 0.6939358178060502
  rhythmicContrast: 0.5197006256785244
purpose: []
