name: CalvinKaiKu
favicon: null
layout_spectrum: 1
typography_spectrum: 1
title: Illusionist
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0e0d0b'
    - '#ffffff'
    - '#65586a'
    - '#ffc7a2'
    - '#ce8656'
  brandStrength: 0.31154339388012886
  lightness: 0.257666630204767
  saturation: 0.6939358178060502
  rhythmicContrast: 0.5197006256785244
purpose: []
